# Generated by Django 5.0.3 on 2024-03-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('node_id', models.IntegerField(blank=True, null=True)),
                ('IP', models.GenericIPAddressField()),
                ('PORT', models.IntegerField(default=5000)),
                ('status', models.TextField(default='Offline', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_id', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
